
//randomize_cells();
randomize_cells_hills(.1);
plot_cells_page();
//randomize_cells_no_fog();
//let f = random_rule();
let f = boring_rule();
f[flat + flat + flat + flat] =  flat
f[flat + flat + flat +  fog] =  flat;
f[flat + flat + flat + hill] =  hill;
f[flat + flat +  fog + flat] =  fog;
f[flat + flat +  fog +  fog] =  fog;
f[flat + flat +  fog + hill] =  hill;
f[flat + flat + hill + flat] =  flat;
f[flat + flat + hill +  fog] =  fog;
f[flat + flat + hill + hill] =  hill;
f[flat +  fog + flat + flat] =  flat;
f[flat +  fog + flat +  fog] =  fog;
f[flat +  fog + flat + hill] =  hill;
f[flat +  fog +  fog + flat] =  fog;
f[flat +  fog +  fog +  fog] =  fog;
f[flat +  fog +  fog + hill] =  hill;
f[flat +  fog + hill + flat] =  flat;
f[flat +  fog + hill +  fog] =  flat;
f[flat +  fog + hill + hill] =  hill;
f[flat + hill + flat + flat] =  flat;
f[flat + hill + flat +  fog] =  fog;
f[flat + hill + flat + hill] =  hill;
f[flat + hill +  fog + flat] =  flat;
f[flat + hill +  fog +  fog] =  fog;
f[flat + hill +  fog + hill] =  hill;
f[flat + hill + hill + flat] =  flat;
f[flat + hill + hill +  fog] =  fog;
f[flat + hill + hill + hill] =  hill;
f[ fog + flat + flat + flat] =  fog;
f[ fog + flat + flat +  fog] =  fog;
f[ fog + flat + flat + hill] =  hill;
f[ fog + flat +  fog + flat] =  fog
f[ fog + flat +  fog +  fog] =  fog;
f[ fog + flat +  fog + hill] =  hill;
f[ fog + flat + hill + flat] =  flat;
f[ fog + flat + hill +  fog] =  flat;
f[ fog + flat + hill + hill] =  hill;
f[ fog +  fog + flat + flat] =  flat;
f[ fog +  fog + flat +  fog] =  fog;
f[ fog +  fog + flat + hill] =  hill;
f[ fog +  fog +  fog + flat] =  fog;
f[ fog +  fog +  fog +  fog] =  flat;
f[ fog +  fog +  fog + hill] =  hill;
f[ fog +  fog + hill + flat] =  flat;
f[ fog +  fog + hill +  fog] =  flat;
f[ fog +  fog + hill + hill] =  hill;
f[ fog + hill + flat + flat] =  flat;
f[ fog + hill + flat +  fog] =  fog;
f[ fog + hill + flat + hill] =  hill;
f[ fog + hill +  fog + flat] =  flat;
f[ fog + hill +  fog +  fog] =  fog;
f[ fog + hill +  fog + hill] =  hill;
f[ fog + hill + hill + flat] =  fog;
f[ fog + hill + hill +  fog] =  fog;
f[ fog + hill + hill + hill] =  hill;
f[hill + flat + flat + flat] =  fog;
f[hill + flat + flat +  fog] =  fog;
f[hill + flat + flat + hill] =  hill;
f[hill + flat +  fog + flat] =  flat;
f[hill + flat +  fog +  fog] =  fog;
f[hill + flat +  fog + hill] =  hill;
f[hill + flat + hill + flat] =  fog;
f[hill + flat + hill +  fog] =  fog;
f[hill + flat + hill + hill] =  hill;
f[hill +  fog + flat + flat] =  fog;
f[hill +  fog + flat +  fog] =  fog;
f[hill +  fog + flat + hill] =  hill;
f[hill +  fog +  fog + flat] =  flat;
f[hill +  fog +  fog +  fog] =  fog;
f[hill +  fog +  fog + hill] =  hill;
f[hill +  fog + hill + flat] =  flat;
f[hill +  fog + hill +  fog] =  flat;
f[hill +  fog + hill + hill] =  hill;
f[hill + hill + flat + flat] =  flat;
f[hill + hill + flat +  fog] =  fog;
f[hill + hill + flat + hill] =  hill;
f[hill + hill +  fog + flat] =  flat;
f[hill + hill +  fog +  fog] =  fog;
f[hill + hill +  fog + hill] =  hill;
f[hill + hill + hill + flat] =  flat;
f[hill + hill + hill +  fog] =  fog;
f[hill + hill + hill + hill] =  hill;
////Sebastian, you can replace the random rule, piece by piece, here. I will put in a few examples
//f[fog + fog + fog + hill] = hill; //the order matters.this is a hill with fog above it. 
//let interval = setInterval(update, delay);
let interval = 0;
function update() {
    plot_cells_page();
    apply_rule(f);
    random_fog(chance);
}
